#!/usr/bin/env ruby
print "\nRunning tests...\n"

def assert_equals(given, expected, test_name)
  result = eval(given)

  if result == expected
    print "\e[32m#{test_name} passes!\e[0m\n"
  else
    print "\e[31m#{test_name} fails! Expected:#{expected}, got #{result}\e[0m\n"
  end

rescue LoadError => e
  print "\e[31m#{test_name} fails! Expected:#{expected}, got #{e}\e[0m\n"
rescue StandardError => e
  print "\e[31m#{test_name} fails! Expected:#{expected}, got #{e}\e[0m\n"
end

tests = {
  "1.0" => ["require('./calculator')", true],
  "1.1" => ["multiply", 0],
  "1.2" => ["multiply(2)", 0],
  "1.3" => ["multiply(2,3)", 6],
  "1.4" => ["multiply(TWO,THREE)", 6]
}

tests.each do |exercise, test|
  assert_equals(test[0], test[1], exercise)
end